# Generated by Django 4.2.4 on 2023-08-23 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('info', models.TextField()),
                ('history', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок')),
                ('text', models.TextField()),
                ('create_date', models.DateTimeField(auto_now=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Обявление',
                'verbose_name_plural': 'Обявление',
                'ordering': ('-create_date',),
            },
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director', models.CharField(blank=True, max_length=200, null=True)),
                ('director_info', models.TextField()),
                ('d_img', models.ImageField(blank=True, default='avatars/default.png', null=True, upload_to='', verbose_name='Картинки')),
                ('ibo', models.CharField(blank=True, max_length=200, null=True)),
                ('ibo_info', models.TextField()),
                ('ibo_img', models.ImageField(blank=True, default='avatars/default.png', null=True, upload_to='', verbose_name='Картинки')),
                ('e_res', models.CharField(blank=True, max_length=200)),
                ('e_res_info', models.TextField(blank=True)),
                ('e_res_img', models.ImageField(blank=True, default='avatars/default.png', upload_to='', verbose_name='Картинки')),
            ],
        ),
    ]
