# Generated by Django 4.2.4 on 2023-08-23 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_about_ads_structure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structure',
            name='d_img',
            field=models.ImageField(blank=True, default='avatars/default.png', null=True, upload_to='avatars/', verbose_name='Картинки'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='e_res_img',
            field=models.ImageField(blank=True, default='avatars/default.png', upload_to='avatars/', verbose_name='Картинки'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='ibo_img',
            field=models.ImageField(blank=True, default='avatars/default.png', null=True, upload_to='avatars/', verbose_name='Картинки'),
        ),
    ]
