# Generated by Django 3.2 on 2023-11-16 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_history_remove_about_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'О библиотеки', 'verbose_name_plural': 'О библиотеки'},
        ),
    ]
