# Generated by Django 3.2 on 2023-11-21 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20231116_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='info_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='info_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='title_ky',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='title_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ads',
            name='text_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ads',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ads',
            name='title_ky',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='ads',
            name='title_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='text_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='catalog',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='catalog',
            name='title_ky',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='catalog',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='text_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='text_ky',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ky',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='readers',
            name='text_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='readers',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='structure',
            name='director_info_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='structure',
            name='director_info_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='structure',
            name='e_res_info_ky',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='structure',
            name='e_res_info_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='structure',
            name='ibo_info_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='structure',
            name='ibo_info_ru',
            field=models.TextField(null=True),
        ),
    ]
